### ISSUE TITLE
ストレージの X,Y_Power が存在しない状態で実行されると、ノックバックされない

### ISSUE THREAD

**Issue by uebpiick** [churura/MC-KnockBackun#1]
最初にロードした時はストレージが無いみたいなので、何も設定せずに実行した一回目は、ノックバックしませんね。

一回実行しちゃえば、[get_storageの11行目](https://github.com/churura/MC-KnockBackun/blob/9f1c5b80d1298f12337375546e5f05b3b088939c/data/knockbackun/functions/mob/core/get_storage.mcfunction#L11)でデフォルトに設定されるので、二回目以降は`X_Power`か`Y_Power`を消さなければ起こらないんですが、一応バグなので報告しときます。

**Comment by churura** [comment]
バグ報告ありがとうございます。
報告頂いたバグの修正を含む [KnockBackun_v1.1](https://github.com/churura/MC-KnockBackun/releases/tag/v1.1) を公開しました。修正・変更点についてはREADMEの [更新](https://github.com/churura/MC-KnockBackun/blob/main/README.md#%E6%9B%B4%E6%96%B0) をご覧ください。
